services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo_server

  mongo_server:
    image: mongo:6.0
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: